### ISSUE TITLE
Revise too much deploy

### ISSUE THREAD

**Issue by pankona** [pankona/KonaReflection#57]
Every push and pr is currently the target of CI (and deploy).
It means one PR executes CI and deploy twice, that means 2 apks will be deployed.

Following URL indicates the way to avoid this issue with environment variable.
http://c-note.chatwork.com/post/82875125805/travis-ci-ios-testflight

**Comment by pankona** [comment]
いまどうなっちゃうかと言うと...
- PRに追いPUSHすると、APKが2個デプロイされる
- なぜなら、PUSHについて一回、PRの確認で一回、の計2回CIが走るため

**Comment by pankona** [comment]
どうなってほしいかというと...
- 2回デプロイするのはやめてほしい。PUSH毎に2回CIしてもいい。
- masterにマージしたときもCI、デプロイしてほしい。

**Comment by pankona** [comment]
[上記記載のURL](http://c-note.chatwork.com/post/82875125805/travis-ci-ios-testflight)から抜粋。
以下のようなやり方で場合分けが出来る。

``` yml
after_success:
- '[ "$TRAVIS_BRANCH" == "master" -o "$TRAVIS_BRANCH" == "develop" ] && make testflight'
after_script:
- '[ "$TRAVIS_BRANCH" == "master" -o "$TRAVIS_BRANCH" == "develop" ] && make remove-certificates'
```
